kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operatorgroup-sa
  namespace: example-operator
subjects:
- kind: ServiceAccount
  name: operatorgroup-sa
roleRef:
  kind: Role
  name: operatorgroup-sa
  apiGroup: rbac.authorization.k8s.io
